include colors.conf
include fonts.conf

cursor_shape block
cursor_beam_thickness 6

scrollback_lines 2000

url_style straight

copy_on_select clipboard

remember_window_size  no
initial_window_width  785
initial_window_height 450

window_padding_width 10

allow_remote_control yes

