# Kitty Terminal Configuration


font_family      		JetBrainsMono Nerd Font
font_size        		14.0
bold_font        		auto
italic_font      		auto
bold_italic_font 		auto

background_opacity 		0.85

window_padding_width	10

# BEGIN_KITTY_THEME
# One Dark
include current-theme.conf
# END_KITTY_THEME

