#! /bin/sh

killall -9 polkit-gnome-authentication-agent-1 picom dunst polybar
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-gnome/polkit-authentication-agent-1 &
nitrogen --restore
dunst &
mpd &
picom -b
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6

bsp-layout set tall 1
bsp-layout set tall 2
bsp-layout set tall 3
bsp-layout set tall 4
bsp-layout set tall 5
bsp-layout set tall 6

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color "#61afef"
bspc config normal_border_color "#444444"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a Lxappearance state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
