live_config_reload = true

[env]
TERM = "alacritty"

[window]
position = "None"
dynamic_padding = true
decorations = "full"
opacity = 0.75
blur = false
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "None"

[window.class]
instance = "Alacritty"
general = "Alacritty"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12

[scrolling]
history = 10_000
multiplier = 3

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 17
builtin_box_drawing = true

[font.normal]
family = "CodeNewRoman Nerd Font"

[font.bold]
family = "CodeNewRoman Nerd Font"

[font.italic]
family = "CodeNewRoman Nerd Font"

[font.bold_italic]
family = "CodeNewRoman Nerd Font"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors]
[[colors.indexed_colors]]
index = 16
color = "0xff9e64"

[[colors.indexed_colors]]
index = 17
color = "0xdb4b4b"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.normal]
black = "0x15161E"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"
