[colors.bright]
black = "0x555555"
blue = "0x5555ff"
cyan = "0x55ffff"
green = "0x55ff55"
magenta = "0xff55ff"
red = "0xff5555"
white = "0xffffff"
yellow = "0xffff55"

[colors.normal]
black = "0x000000"
blue = "0x7777dd"
cyan = "0x7acaca"
green = "0x55cc55"
magenta = "0xcc55cc"
red = "0xcc5555"
white = "0xcccccc"
yellow = "0xcdcd55"

[colors.primary]
background = "0x000000"
foreground = "0xb3b3b3"
