[colors.bright]
black = "0x444444"
blue = "0x5555ff"
cyan = "0x00AAAA"
green = "0x00AA00"
magenta = "0xCC00CC"
red = "0xff5555"
white = "0xcccccc"
yellow = "0xffff55"

[colors.normal]
black = "0x101010"
blue = "0x5555ff"
cyan = "0x00aaaa"
green = "0x00AA00"
magenta = "0xCC00CC"
red = "0xff5555"
white = "0xefefef"
yellow = "0xffff55"

[colors.primary]
background = "0x101010"
foreground = "0xcccccc"
