[font]
size = 15

[font.bold]
family = "MesloLGS Nerd Font Mono"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"

[font.italic]
family = "MesloLGS Nerd Font Mono"

[font.normal]
family = "MesloLGS Nerd Font Mono"
